### ISSUE TITLE
Sapling 1.1.3 permantly grabs a thread

### ISSUE THREAD

**Issue by CPagador** [Timmoth/Sapling#11]
I run tournaments with ponder off and 1 thread per engine. Through Task Manager I realized Sapling always use a thread, even when it is not his turn. Is there a way to disable it? The GUI is set to ponder off, of course.

Regards,
Carlos

**Comment by Timmoth** [comment]
Hey Carlos! Thank you so much for including Sapling in your tournament, I can't wait to see how it performs! I can assure you it's not thinking whilst it isn't it's turn but I think I know what the problem may be. 

It will be this loop:
https://github.com/Timmoth/Sapling/blob/fc41d026d0e6d5bd8f34d1eb652eaee2cb4ab907/Sapling/Program.cs#L115

It's waiting to receive a command but It's extremely inefficient and essentially looping and checking if it got a message at a very high rate. It will be an easy fix. I'll get it done tonight and ping you when it's sorted. 

Thanks again for alerting me of this!

**Comment by Timmoth** [comment]
@CPagador that should be fixed in v1.1.4
https://github.com/Timmoth/Sapling/releases/tag/Sapling-1.1.4

Please let me know if it's still causing you issues or if there are any other problems you've noticed. 

Also would I be able to see the results of the tournament once it's complete?

**Comment by CPagador** [comment]
Hi Tim,

Yes, you can follow the results here:

https://talkchess.com/forum3/viewtopic.php?t=84301

An older version compiled by Jim Ablett participated in the PL12, version 1.1.3 is competing in PL11. I'll use the latest version tomorrow, when PL10 starts. I anticipate to say that it will pass to the next phase because it is very strong. :D

Best regards,
Carlos

P.S.: Could you generate an AVX2 and/or BMI2 binary? I think it could be faster on my PC.

**Comment by CPagador** [comment]
> @CPagador that should be fixed in v1.1.4 https://github.com/Timmoth/Sapling/releases/tag/Sapling-1.1.4
> 
> Please let me know if it's still causing you issues or if there are any other problems you've noticed.
> 
> Also would I be able to see the results of the tournament once it's complete?

It is working fine now. Thank you.

**Comment by Timmoth** [comment]
> P.S.: Could you generate an AVX2 and/or BMI2 binary? I think it could be faster on my PC.

All binaries in the release make use of AVX2 / BMI2 (amongst other extensions) the vast majority of modern cpus will support the AVX256 version (e.g Sapling_win_x64.exe), but if your CPU supports AVX512 use that version since it will be considerably stronger! (e.g Sapling_win_x64_avx512.exe)

**Comment by Timmoth** [comment]
> An older version compiled by Jim Ablett participated in the PL12, version 1.1.3 is competing in PL11. I'll use the latest version tomorrow, when PL10 starts. I anticipate to say that it will pass to the next phase because it is very strong. :D

Oh yeah since 2024-09-19-47 it's a lot stronger at least +200ELO I'm very excited to see it compete in it's first tournament, I'll be checking in daily!

**Comment by CPagador** [comment]
> > P.S.: Could you generate an AVX2 and/or BMI2 binary? I think it could be faster on my PC.
> 
> All binaries in the release make use of AVX2 / BMI2 (amongst other extensions) the vast majority of modern cpus will support the AVX256 version (e.g Sapling_win_x64.exe), but if your CPU supports AVX512 use that version since it will be considerably stronger! (e.g Sapling_win_x64_avx512.exe)

Ah ok, my cpu does not support AVX512, so I will keep using Sapling_win_x64.exe

**Comment by Timmoth** [comment]
Been absolutely fantastic to keep tabs on your tournament @CPagador I check your posts multiple times a day, if i'm not mistaken Sapling hasn't lost a game yet? Very excited to see how it pans out! 

(closing this issue, feel free to re-open)

P.S Sapling has a new version out v1.1.5 in case it's possible to update it in your tournament

**Comment by CPagador** [comment]
I just resumed the tournament with version 1.1.8. Sapling won his first game against DirtyBit 0.39.5. Congrats!

**Comment by Timmoth** [comment]
Amazing! Can't wait to see the results for PL5! 

Out of interest what ELO is DirtyBit? I couldn't find a figure online

**Comment by CPagador** [comment]
> Amazing! Can't wait to see the results for PL5!
> 
> Out of interest what ELO is DirtyBit? I couldn't find a figure online

Close to 2239 CCRL rating:

https://computerchess.org.uk/ccrl/404/

PL4 results already posted:

https://talkchess.com/forum3/viewtopic.php?t=84301&start=10

**Comment by Timmoth** [comment]
@CPagador Really appreciate you keep updating the version in the tournament, it's very motivating! Since I know i'm releasing quite frequently at the moment. I've got a training session or two and new net left then it'll probably slow down.
