### ISSUE TITLE
chess position types : new eval

### ISSUE THREAD

**Issue by tissatussa** [Timmoth/Sapling#14]
just an idea -

being a chess player and a programmer, i imagine position types for an engine to evaluate.
if 'position types' exist, how to determine / define them ?

let's say 5 types exist - whatever they are and how we ever know them .. then it's too simple assigning one type to a position, because many positions can exist on the chess board and they're all some mixture of many parameters .. but what if we define each type as a combination of 3 factors, i propose : 'regarding pawns', 'regarding pieces' and 'regarding the king'. That's logical : this way these factors (values between 0 and 1) will be / have a 'combined value' being 'relational' : proportions.

then train an NN !?
(how is recursion involved ?)

---

https://github.com/user-attachments/assets/717b21a1-575d-4f6d-9d9e-627bfe8c627f

it would be awesome if i could find anyone on this earth to deduce those 5 ..

**Comment by tissatussa** [comment]
i just found this info on https://github.com/tsoj/Nalwald :

_Some noteworthy features of Nalwald:_

- _Piece-relative PSTs are piece square tables that are different depending on which square another piece is. They are added together for all pieces of all piece types._
- _Futility reductions are an improvement to futility pruning. Here not only are moves skipped that are likely to be much worse than alpha. Additionally, moves that are likely slightly worse than alpha get their depth reduced accordingly to how bad they are expected to be._
- _Hash result futility pruning uses hash table entries that have not a depth high enough to adjust alpha or beta, or to return a value immediately. Rather, depending on their depth, the value gets only used, when the margin to alpha or beta is big enough._
- _3x3 pawn structure tables are a way to evaluate the structure of multiple pawns. For this a 3x3 mask is used on any square for which at least two pawns (ours or enemy) fall into this mask. The pawns in that mask can be used to calculate an exact index for this structure of pawns in a 3x3 space. This index can be used to access a table, which contains values to evaluate this pawn structure. This table can then be optimized using a method like gradient descent._

any association with my subject ?

**Comment by Timmoth** [comment]
> Piece-relative PST

A very important part of hand crafted evaluation, Sapling had these when it was iBlunder, but since moving to NNUE it's not needed!

> Futility reductions are an improvement to futility pruning

Very powerful, Sapling has them!

> Hash result futility pruning

Interesting, Sapling does cut off on a transposition hit less then alpha or greater then beta, but i've not tried it with a margin.

> 3x3 pawn structure tables are a way to evaluate the structure of multiple pawns 

Not come across this one, but it sounds like a feature of an advanced HCE, again NNUE deals with this internally

**Comment by tissatussa** [comment]
Let's close this one.

In the meantime Sapling has 3378 rating on the CCRL 40/15 list !
https://computerchess.org.uk/ccrl/4040/rating_list_all.html
