### ISSUE TITLE
Gauntlet 5m3s against Komodo versions

### ISSUE THREAD

**Issue by tissatussa** [Timmoth/Sapling#16]
Here are the results of a small Gauntlet tournament against several Komodo versions, Sapling v1.1.4 played White.
The games had this starting position :

![position-against-8-Komodo-versions](https://github.com/user-attachments/assets/6fa1d470-7458-4f6c-99c4-33de6b7df358)

rnbqkb1r/ppp1pppp/5n2/3p2B1/3P4/4P3/PPP2PPP/RN1QKBNR b KQkq - 0 3

```
Rank Name                           Rating   Elo     +/-   Games   Points   Score    Draw
-----------------------------------------------------------------------------------------
   0 Sapling v1.1.4 NNUE              3100   -89     190       8      3.0   37.5%   50.0% 

   1 Komodo Dragon MCTS positional    3592   inf     nan       1      1.0  100.0%    0.0% 
   2 Komodo Dragon NN default         3592   inf     nan       1      1.0  100.0%    0.0% 
   3 Komodo v12.1.1                   3321   inf     nan       1      1.0  100.0%    0.0% 
   4 Komodo Dragon HCE default        3592     0       0       1      0.5   50.0%  100.0% 
   5 Komodo Dragon MCTS default       3592     0       0       1      0.5   50.0%  100.0% 
   6 Komodo v13.02 MCTS               3523     0       0       1      0.5   50.0%  100.0% 
   7 Komodo v13.02                    3523     0       0       1      0.5   50.0%  100.0% 
   8 Komodo v12.1.1 MCTS              3321  -inf     nan       1      0.0    0.0%    0.0% 
```

Sapling v1.1.4 could only win against Komodo v12.1.1 MCTS, it lost 3 games and drew 4.
Another indication Sapling is strong !
Download PGN here : [Gauntlet-5m3s-Sapling-1-1-4-against-8-Komodo-versions-d4-Nf6-Bg5-d5-e3.zip](https://github.com/user-attachments/files/17201218/Gauntlet-5m3s-Sapling-1-1-4-against-8-Komodo-versions-d4-Nf6-Bg5-d5-e3.zip)

btw.
i used the asset binary because i'm unable to compile the v1.1.4 source on Linux yet.
Hash 256 Mb, 2 threads.

**Comment by Timmoth** [comment]
I'm very pleased with even a draw against Komodo! Thanks for sharing the results!
