### ISSUE TITLE
v1.1.5 disconnects at move 11

### ISSUE THREAD

**Issue by tissatussa** [Timmoth/Sapling#17]
This happens with v1.1.5, i never encountered something like it with any engine : at move 11 it disconnects, no sooner, no later.
I reproduced this 6 (!) times with a 5m3s games, Sapling playing White and Black, with and without start FEN : [Sapling-1-1-5-disconnects-around-move-11.zip](https://github.com/user-attachments/files/17256179/Sapling-1-1-5-disconnects-around-move-11.zip) all games had the same result, it's weird.

Note: i use your x64 Linux asset, because i can't compile the v1.1.5 source, it gives many errors.

**Comment by Timmoth** [comment]
OH no!! Not sure how that's slipped through. I'll investigate asap, in the mean time I've removed the release for v1.1.5 

Thanks for the report, not entirely sure what could be happening there.

**Comment by Timmoth** [comment]
Would you be able to send the file generated in the logs for that game (if you still have it)

**Comment by tissatussa** [comment]
> Would you be able to send the file generated in the logs for that game (if you still have it)

here : [logs.zip](https://github.com/user-attachments/files/17256869/logs.zip)
it's from another run ..

**Comment by tissatussa** [comment]
I tried to compile with your Makefile, but it gives many warnings and errors.
However, i'm able to do this command (from the README) : it gives only warnings, and ends without coming to the prompt, so did 'uci' and indeed it runs :

```
$ dotnet run --project ./Sapling/Sapling.csproj --configuration Release
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Tuning/SpsaOptions.cs(15,23): warning CS8618: Non-nullable field 'Name' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Tuning/SpsaOptions.cs(16,23): warning CS8618: Non-nullable field 'Type' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Tuning/SpsaOptions.cs(17,23): warning CS8618: Non-nullable field 'DefaultValue' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Tuning/SpsaOptions.cs(18,23): warning CS8618: Non-nullable field 'MinValue' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Tuning/SpsaOptions.cs(19,23): warning CS8618: Non-nullable field 'MaxValue' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Tuning/SpsaOptions.cs(20,26): warning CS8618: Non-nullable field 'FieldHandle' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Evaluation/NnueWeights.cs(56,20): warning CS8602: Dereference of a possibly null reference. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/RepetitionDetector.cs(92,26): warning CS8509: The switch expression does not handle all possible values of its input type (it is not exhaustive). For example, the pattern '0' is not covered. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling/UciEngine.cs(29,23): warning CS8602: Dereference of a possibly null reference. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling/Sapling.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling/Program.cs(27,34): warning CS8602: Dereference of a possibly null reference. [/home/roelof/Compiled/Sapling-Sapling-1.1.5/Sapling/Sapling.csproj]
uci
id name Sapling 1-1-5
id author Tim Jones
option name Threads type spin default 1 min 1 max 1024
option name Ponder type check default false
option name Hash type spin default 319 min 32 max 2046
option name ReverseFutilityPruningMargin type spin default 75 min 10 max 100
option name ReverseFutilityPruningDepth type spin default 7 min 1 max 10
option name NullMovePruningDepth type spin default 2 min 1 max 10
option name NullMovePruningReductionA type spin default 3 min 1 max 10
option name NullMovePruningReductionB type spin default 4 min 1 max 10
option name NullMovePruningReductionC type spin default 3 min 1 max 10
option name RazorMarginA type spin default 125 min 10 max 400
option name RazorMarginB type spin default 300 min 10 max 400
option name InternalIterativeDeepeningDepth type spin default 2 min 1 max 10
option name LateMovePruningConstant type spin default 8 min 1 max 10
option name LateMoveReductionMinDepth type spin default 3 min 1 max 10
option name LateMoveReductionMinMoves type spin default 2 min 1 max 10
option name HistoryHeuristicMaxHistory type spin default 8192 min 7000 max 10000
option name HistoryHeuristicBonusMax type spin default 640 min 500 max 1000
option name HistoryHeuristicBonusCoeff type spin default 80 min 10 max 100
option name MoveOrderingWinningCaptureBias type spin default 10000000 min 500000 max 10000000
option name MoveOrderingLosingCaptureBias type spin default 16000 min 10000 max 30000
option name MoveOrderingPromoteBias type spin default 600000 min 70000 max 700000
option name MoveOrderingKillerABias type spin default 500000 min 70000 max 600000
option name MoveOrderingKillerBBias type spin default 250000 min 70000 max 300000
option name MoveOrderingCounterMoveBias type spin default 65000 min 20000 max 80000
option name InterestingNegaMaxMoveScore type spin default 16000 min 10000 max 30000
option name InterestingQuiescenceMoveScore type spin default 16000 min 10000 max 30000
uciok
quit
```

It seems in 'Sapling/bin/Release/net8.0/' a bunch of files is created (.json & .dll & more) with 'Sapling' being the executable : when i go into this folder and run that, it succeeds and i can use it in CuteChess. But i want a single binary, so i tried compiling with options like --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -o ./Sapling-single-binary but no combination gives the desired result .. how can i create a single binary ?

**Comment by tissatussa** [comment]
i just ran CuteChess GUI in a debugger (lldb-17) and let v1.1.5 play a game .. again at move 11 (!?) it disconnects, but lldb gives only this :

```
$ lldb-17 /home/roelof/Apps/cutechess-1.3.1/cutechess-gui
(lldb) target create "/home/roelof/Apps/cutechess-1.3.1/cutechess-gui"
Current executable set to '/home/roelof/Apps/cutechess-1.3.1/cutechess-gui' (x86_64).
(lldb) run
Process 32125 launched: '/home/roelof/Apps/cutechess-1.3.1/cutechess-gui' (x86_64)
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3632, resource id: 11270034, major code: 40 (TranslateCoords), minor code: 0
Process 32125 stopped and restarted: thread 15 received signal: SIGCHLD
Terminating process of engine Sapling v1.1.5 NNUE(0)
```

**Comment by tissatussa** [comment]
here's the concerning log file : [10-4-2024_12-52_PM9171b843-345e-4dab-abe5-42655a2d55bd.zip](https://github.com/user-attachments/files/17257253/10-4-2024_12-52_PM9171b843-345e-4dab-abe5-42655a2d55bd.zip)

**Comment by tissatussa** [comment]
btw. i used the default UCI settings, threads 1.

**Comment by Timmoth** [comment]
I've tracked down two potential causes of the error you found.
1) The 'Searcher' was causing an 'AccessViolationException' when being disposed. I've fixed it now, though this should only happen when reducing the thread count on a running instance, so not sure if that's what you experienced.
2) If no best move was found it would cause an out of bounds exception by trying to select the first element from an empty list. I've put in some logic to avoid this now under various conditions (like asking for a move when in mate, the search being cancelled or running out of time)

I've also added some better logging / error handling so hopefully if it is neither of those things it should be better equipped to catch it.

Would you be able to try again since you were able to reproduce it reliably and let me know if it's fixed (v1.1.5 in the assets is up to date)

P.S will work on fixing the linux make file tonight

**Comment by tissatussa** [comment]
> I've tracked down two potential causes of the error you found

as you describe those causes they don't seem related to my Issue .. the newest 1.1.5 asset runs fine in CuteChess GUI : i let it play two 5m3s games, the first with default settings playing White from start position, the second with 2 threads playing Black from some starting FEN .. all seems normal, it won both games (against 4KU v5.1) while spending time efficiently in its normal way .. some log files were created but 0 bytes.

**Comment by tissatussa** [comment]
about the 11th move : this is weird, isn't it ? Six times the same Issue .. with that buggy 1.1.5 version, when the engine is to move at 11th, it IMMEDIATELY "disconnects", not during the evaluation of that move.

**Comment by tissatussa** [comment]
> P.S will work on fixing the linux make file tonight

you might consider 'Mono' for Linux users .. anyhow, you will learn new thing when solving this!

**Comment by Timmoth** [comment]
Just to clarify, the new version doesn't experience that bug you mentioned?

**Comment by tissatussa** [comment]
> Just to clarify, the new version doesn't experience that bug you mentioned?

no, the newest 1.1.5 runs fine, no problems of that kind.

**Comment by Timmoth** [comment]
Brilliant thank you for discovering & reporting the issue!

**Comment by tissatussa** [comment]
@Timmoth Although the following information isn't directly related to this Issue, i want to mention it here, because you're constantly working on a newer version, and many techniques are involved.

Once i found the chess engine Akimbo - newest versions use an NN - see https://github.com/jw1912/akimbo 
Its README states :

_Evaluation_

_Up to and including version 1.0.0, all data used was self-generated, starting from material values when akimbo still had an HCE and iteratively generating data and tuning to produce higher quality datasets. The final HCE dataset was then used to train akimbo's first network and further data was then generated._

_This involved hundreds of hours of compute, and got incredibly tedious, so akimbo now uses data produced by Leela Chess Zero._

_Additionally, akimbo uses its own trainer written in Rust and CUDA, bullet, which also used by a number of other engines._

Do you recognise the method used to train an NN and/or use data for it ?
Could this be of any help or give inspiration ?
When i read this, i was thinking about the Sapling NN -- Akimbo is written in Rust though ..

**Comment by Timmoth** [comment]
>Up to and including version 1.0.0, all data used was self-generated, starting from material values when akimbo still had an HCE and iteratively generating data and tuning to produce higher quality datasets. The final HCE dataset was then used to train akimbo's first network and further data was then generated.

Sapling took this one step further, it started with entirely random weights, so at first there was 0 chess knowledge and through iteratively generating new networks it learned all knowledge itself. 

>This involved hundreds of hours of compute, and got incredibly tedious, so akimbo now uses data produced by Leela Chess Zero.

This is the standard path people take, data gen is long and expensive, i spend £400 on cloud servers plus the 4 I had at home for the first few weeks, then I bought two new high powered systems that I also use now. Although Leela data is well believed to be the best dataset so will always beat self gen data but it reduces the unique feeling of your engine since it's learned to play based on the moves of a much stronger engine. I refuse to use it and will keep improving my own net based on self play.

> Additionally, akimbo uses its own trainer written in Rust and CUDA, bullet, which also used by a number of other engines.

I'm using bullet to do the actual training too!

Here's the training log so far:
https://github.com/Timmoth/Sapling/blob/main/Sapling.Engine/Resources/WeightsHistory/log.txt

Probably generated 20bn+ positions over all the iterations, which takes a looong time and i've still got some way to go

**Comment by tissatussa** [comment]
@Timmoth nice info, thanks!

**Comment by Timmoth** [comment]
Yeah that's mine (can you remove from that comment as i don't want it to be public) 
Also where did you find it?

I didn't see it! I'll go have a look now!

**Comment by tissatussa** [comment]
btw. i found it by the '@'info on your GitHub profile ..
