### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by AlexBrunetti** [Timmoth/Sapling#18]
Hello,
to avoid extreme confusion, could you please change the version number when you publish a new executable, even if it's a debug? You could just add a letter or so, like 1.5.1a. It's better to differentiate the programs, for who has already downloaded the previous one.

Thanks.
Alex

**Comment by Timmoth** [comment]
Hey Alex! Yes of course, I will make sure of that from now on.

I'll think of a better naming strategy for stable / experimental builds
