### ISSUE TITLE
max 30 seconds thinking time

### ISSUE THREAD

**Issue by tissatussa** [Timmoth/Sapling#19]
I discovered all (?) Sapling versions have max 30 seconds thinking time. Even when the UCI command `go infinite` is given. I don't recall any engine 'behaves' like this. I think it's better to consider the remaining playing time for that, and somehow decide if there's enough time to complete the evaluation of a next depth.

I guess this is by design, but why ?

**Comment by Timmoth** [comment]
It was an artifact of developing [iblunder.com](https://iblunder.com/) - which the engine was originally built for. But you're right - it shouldn't be in there now - I'll remove it! Thank you again for pointing these things out to me!

**Comment by Timmoth** [comment]
Removed limit in v1.2.0
