### ISSUE TITLE
some test position : find best move

### ISSUE THREAD

**Issue by tissatussa** [Timmoth/Sapling#20]
Lately i follow the development of you Sapling engine, newest is v1.1.8 now .. of the many games (5m+3s) i let Sapling play in CuteChess GUI, one remarkable position occured against Calvin v4.3.0 NNUE (White) :

4kb2/4n2R/pp1p3p/8/6p1/P2N1P1r/1PPBr2P/1K4R1 w - - 1 38

![LiChess-game](https://github.com/user-attachments/assets/9837586e-7b79-45cb-912f-f6123b428ef7)

[ replay game [here](https://lichess.org/hlHL4sG7) / download : [PGN-Calvin-v4.3.0-vs-Sapling-v1.1.5.zip](https://github.com/user-attachments/files/17306962/PGN-Calvin-v4.3.0-vs-Sapling-v1.1.5.zip) ]

At this point we see the evaluation (by SF 16 NNUE) drop, because Calvin made a mistake here : it played Bc1 ? To discover alternative moves and evaluations, i gave this position to a few very strong engines, having MultiPV. It's clear Bb4 is preferred here, it's the only `bestmove`. Here are these results, running in SCID :

![SF-17-Bb4-immediately](https://github.com/user-attachments/assets/9ec82014-a4b8-48e1-b272-fcb41f89b5d9)

![Altair-7-Bb4-immediately](https://github.com/user-attachments/assets/bbf711a3-be9f-456a-9636-cc497c642883)

![Berserk-12-Bb4-immediately](https://github.com/user-attachments/assets/98aa1817-ef5a-414f-b9b6-3d86d45f73c5)

![Komodo-13-Bb4-immediately](https://github.com/user-attachments/assets/d20de80e-2961-4055-8dfc-15dd0ed07230)

Then, to discover if other (strong) engines would find this 'solution', i let many think for 1 minute and logged the outcome : did the engine find Bb4 ? If so, after how many seconds and at which depth ? Of my many gathered (Linux) engines, i picked most NNUE ones and a bunch of other (HCE) engines. The result was astonishing : many strong engines didn't find it, but also many weak engines did .. it seems some variation, probably tactical in nature, it due to rejecting Bb4, i don't know .. here are the 4 result lists, ordered and showing the rating of all engines - they're screenshots of the concerning .csv spreadsheets i made.

Such position is a good example of a .epd / Strategic Test Suite 'puzzle', to determine the strength of an engine.
I think the results are remarkable.
Btw. many engines switch their evaluation & bestmove while increasing depth. I logged the first depth (& concerning duration) at which the engine found Bb4 and didn't change its mind afterwards. 

Sapling versions upto v1.1.1 do NOT find Bb4, the newer ones do !

---

**NN engines which did NOT find Bb4 :**

![no-with-NN](https://github.com/user-attachments/assets/76330b0b-6d5c-4217-ad22-441e54e00855)

---

**NN engines which DID find Bb4 :**

![yes-with-NN](https://github.com/user-attachments/assets/28dc9dfc-d100-413c-91d6-c58d73ddaf06)

---

**non-NN engines which did NOT find Bb4 :**

![no-wo-NN](https://github.com/user-attachments/assets/f4dca677-10ae-4899-acf6-13ee9ea02b4d)

---

**non-NN engines which DID find Bb4 :**

![yes-wo-NN](https://github.com/user-attachments/assets/5670c1b8-8cb5-466b-a898-d6b1ffdf47a9)

**Comment by Timmoth** [comment]
Oh that's awesome! I still have a note to get around to testing all those puzzle positions you told me about, I'm busy trying to tune the engine and train a new net but will try and compile a set and see how it performs. 

I did see this one position in the SF discord:
1r1q1r2/5pk1/p2p1Np1/2pBp2p/1p2P2P/2PP2P1/1P1Q4/2K2R1b w - - 0 29

Mate in 17, but Sapling is unable to find it - apparently it requires a very strong engine to find, maybe after this set of changes it'll be able to do it!

**Comment by tissatussa** [comment]
I'll investigate that FEN.

Regarding the results i gave : some engines give a different result when letting them evaluate my position again .. i have no clue why .. eg. Weiss v2.1-dev : the newest version does find Bb4, but when testing now the same version as i did, it DOES give Bb4 as bestmove, although my log shows it did NOT find it .. strange .. another thing : SF Bluefish (section "non-NN engines which DID find Bb4") has rating 1600, but that's false -- i used a Python script to set the rating, determined by calculating a "simularity factor" of the engine name compared to my other list - this one slipped through..

**Comment by tissatussa** [comment]
> 1r1q1r2/5pk1/p2p1Np1/2pBp2p/1p2P2P/2PP2P1/1P1Q4/2K2R1b w - - 0 29 : Mate in 17 ..

SF 17, among other very strong engines, finds Ng8! bestmove after 1 minute, but not M17 .. maybe when i let it think longer .. i don't think such M[#many] positions are of much use to test an engine, my position with a simple bestmove is more suitable : the Bd2 will have to move, to c1 or f4 or e1 or even c3, and b4 is best. To find the bestmove in a M[#many] position, the engine might have to sacrifice a lot of pieces, as long as it's mate in the end ..

**Comment by tissatussa** [comment]
I just discovered something weird : letting SF 17 NNUE evaluate your "M17 position" in CuteChess GUI, setting time 'infinite', results in M31 at depth 64 (!) after 2 minutes :

![SF-17-tries-to-find-Ng8-M17](https://github.com/user-attachments/assets/839952a1-088b-414d-a906-bfc2c969653b)

but when i let this engine evaluate in SCID, it indeed finds M17, within 6 seconds at depth 47 !? I did my investigations in CuteChess GUI, so does this means all my stats are flawed ? How can this be ?

Regarding Sapling (v1.1.8) : it's unknown your engine will find M# because of its 30-sec-limit .. but it DOES find Ng8 being bestmove !

**Comment by tissatussa** [comment]
> ..testing all those puzzle positions you told me about, I'm busy trying to tune the engine and train a new net but will try and compile a set and see how it performs..

i imagine training a new net is awesome and important, so continue with that .. i really like your approach in this, giving the engine its own style .. i don't know how those STS positions can help to improve an engine, but they're a great test .. however, i think all those (old) STS positions need to be revised, because the average strength of engines has improved over time .. did you create a script / program for that yet ? I remember you wrote that you're working on that too ..

**Comment by Timmoth** [comment]
I haven't yet, but it's on my list! I'm not sure myself how it can be used to improve strength, but it can certainly be used to prevent regression. E.G if it found M17 at depth 20 but now depth 30 after a change It's likely I've made something worse.

**Comment by tissatussa** [comment]
I updated the intro part of this Issue by adding the concerning FEN - it's handy, i forgot ..

In the meantime i use this position for further testing of some (strong) engines, see if they find the solution .. e.g. Bobcat v8.0, an old UCI engine which i fixed for Linux today (see https://github.com/Bobcat/bobcat/issues/3 ) : it can't find Bb4, the engine thinks Bf4 is bestmove - Bobcat v8.0 has rating 2945 at CCRL ..

I'm closing this Issue now.
I hope those STS epd suites will inspire !
