### ISSUE TITLE
this game it couldn't win

### ISSUE THREAD

**Issue by tissatussa** [Timmoth/Sapling#6]
While being intrigued by the strength and playing style of your Sapling NN chess engine, i let it play many 5m+3s games against other engines during the last days - see also my #4 . Sapling wins most of those battles, slowly outperforming the opponent .. often too slow, if you ask me : it loves to keep threatening and postpones taking advantages and it does this into extremes .. i've not seen such engine "behaviour" before, Sapling has a rather unique style in my eyes. At this moment i estimate its (v1.0.x) rating 3100+

Here's one game it should clearly have won, but it couldn't :

[[ replay game ]](https://lichess.org/BTrGXm7x)

```
[Event "engine vs engine"]
[Site "Holland @ https://lichess.org/BTrGXm7x "]
[Date "2024.09.20"]
[Round "?"]
[White "Sapling v1.0.4 NNUE"]
[Black "PeSTO v2.210"]
[WhiteElo "3100"]
[BlackElo "2992"]
[Result "1/2-1/2"]
[ECO "C79"]
[GameDuration "00:15:14"]
[Opening "Ruy Lopez"]
[PlyCount "129"]
[TimeControl "300+3"]
[Variation "Steinitz defense deferred (Russian defense)"]

1. e4 {+0.52/23 13s} e5 {-0.17/20 7.5s} 2. Nf3 {+0.47/24 12s} Nc6 {-0.04/21 11s}
3. Bb5 {+0.32/23 12s} a6 {-0.06/20 4.7s} 4. Ba4 {+0.36/24 12s}
Nf6 {-0.07/19 9.1s} 5. O-O {+0.28/24 11s} d6 {-0.04/20 4.4s}
6. c3 {+0.57/24 11s} Be7 {-0.19/19 6.9s} 7. Re1 {+0.70/25 11s}
b5 {-0.09/19 5.2s} 8. Bc2 {+0.68/26 10s} Bg4 {-0.09/20 12s} 9. d3 {+0.62/23 10s}
Bh5 {-0.29/20 13s} 10. Nbd2 {+0.56/25 10s} d5 {-0.24/21 7.4s}
11. Nf1 {+0.65/24 9.8s} dxe4 {-0.11/21 11s} 12. dxe4 {+0.74/25 9.5s}
Qxd1 {-0.23/22 24s} 13. Rxd1 {+0.77/23 9.3s} O-O {-0.32/20 10s}
14. Ne3 {+0.74/24 9.1s} Rad8 {-0.15/22 16s} 15. Rxd8 {+0.80/22 8.9s}
Rxd8 {-0.21/24 12s} 16. Kf1 {+0.79/21 8.7s} Bc5 {+0.02/19 5.3s}
17. Ne1 {+0.51/24 8.5s} a5 {+0.10/20 6.0s} 18. f3 {+1.19/23 8.3s}
h6 {0.00/21 17s} 19. Nd3 {+1.39/22 8.2s} Ba7 {-0.08/19 9.4s}
20. Bd2 {+1.40/23 8.0s} Bg6 {-0.25/20 7.7s} 21. Ke2 {+1.62/23 7.8s}
a4 {-0.20/20 11s} 22. b3 {+1.83/24 7.7s} a3 {-0.28/20 8.7s}
23. Bc1 {+2.28/24 7.5s} Ra8 {-0.50/21 13s} 24. b4 {+2.75/21 7.4s}
Bxe3 {-0.44/20 5.0s} 25. Bxe3 {+3.20/24 7.2s} Bh5 {-0.58/22 6.8s}
26. Nc5 {+4.07/22 7.1s} Ne7 {-0.55/23 11s} 27. Bd3 {+4.35/24 6.9s}
c6 {-0.98/20 6.2s} 28. c4 {+4.36/26 6.8s} Bg6 {-1.19/20 5.3s}
29. Rc1 {+4.72/23 6.7s} bxc4 {-1.37/24 6.5s} 30. Bxc4 {+4.65/24 6.6s}
h5 {-1.37/24 6.7s} 31. Rd1 {+4.91/21 6.4s} h4 {-1.74/26 11s}
32. Rd6 {+5.27/21 6.3s} Kh7 {-1.84/23 9.6s} 33. Bg5 {+5.28/24 6.2s}
Ne8 {-1.81/24 7.5s} 34. Bxe7 {+5.36/27 6.1s} Nxd6 {-1.98/25 6.7s}
35. Bxd6 {+5.54/26 6.0s} f6 {-2.01/26 4.3s} 36. Nb7 {+5.56/24 5.9s}
Be8 {-2.16/24 4.2s} 37. Bc5 {+5.89/28 5.8s} Bd7 {-1.86/22 3.9s}
38. Nd6 {+5.96/23 5.7s} g5 {-2.16/26 5.4s} 39. h3 {+6.29/28 5.6s}
Kg6 {-2.67/26 4.0s} 40. Kd2 {+6.03/27 5.5s} Rd8 {-2.71/25 6.5s}
41. Kc2 {+6.14/28 5.5s} Ra8 {-2.93/24 4.1s} 42. Kb3 {+6.30/28 5.4s}
Kh6 {-3.14/24 4.6s} 43. Kc3 {+6.30/26 5.3s} Kg6 {-2.79/23 4.4s}
44. Bf7+ {+6.22/28 5.2s} Kh6 {-2.91/24 6.4s} 45. Bb3 {+6.23/27 5.1s}
Kg7 {-2.75/26 4.9s} 46. Bb6 {+6.23/27 5.1s} Rb8 {-2.81/24 5.6s}
47. Ba7 {+6.23/28 5.0s} Ra8 {-2.83/26 6.6s} 48. Bc5 {+6.22/30 4.9s}
Kg6 {-2.82/26 8.6s} 49. Bc4 {+6.22/27 4.9s} Rh8 {-2.98/28 13s}
50. Kb3 {+6.22/30 4.8s} Ra8 {-3.17/25 5.6s} 51. Bb6 {+6.22/29 4.7s}
Kg7 {-2.77/24 5.7s} 52. Be3 {+6.21/29 4.7s} Kg6 {-3.08/26 6.1s}
53. Bf7+ {+5.96/28 4.6s} Kg7 {-2.67/22 2.7s} 54. Bc5 {+5.97/31 4.6s}
Kh7 {-2.92/23 5.5s} 55. Nf5 {+6.03/28 4.5s} Ra6 {-2.92/24 4.8s}
56. Bc4 {+6.03/30 4.5s} Ra8 {-3.06/26 2.4s} 57. Kc3 {+6.03/31 4.4s}
Kg6 {-2.47/26 7.5s} 58. Nd6 {+6.03/30 4.4s} Rh8 {0.00/46 2.4s}
59. Bb3 {+6.03/29 4.3s} Ra8 {0.00/42 2.9s} 60. Bf7+ {+6.03/29 4.3s}
Kh6 {0.00/52 2.2s} 61. Kc2 {+6.03/29 4.2s} Kg7 {-2.19/22 3.4s}
62. Bb3 {+6.03/30 4.2s} Kg6 {-2.58/24 3.7s} 63. Kd3 {+6.03/31 4.2s}
Kg7 {-2.34/22 8.0s} 64. Bc4 {+6.03/30 4.1s} Kg6 {-2.56/24 3.2s}
65. Kc3 {+6.03/31 4.1s, Draw by 3-fold repetition} 1/2-1/2
```

The engine didn't find a plan to convert its great advantage (+6 !) into a win and drew this game by 3-fold repetition. That's a pitty, and i let the newest Stockfish 17 (rating 3600?!) show that White can win this position and how. It's against the same opponent engine.

I let the game start after 58. Nd6 : r7/3b4/2pN1pk1/2B1p1p1/1PB1P2p/p1K2P1P/P5P1/8 b - - 0 1
Black to play.

![sapling-should-win-with-white](https://github.com/user-attachments/assets/824a20c8-fc2f-4bdc-a442-baf37ec5daf1)

LiChess graph of the Sapling game. At the end White is +6 (= diagram).

![sapling-clearly-winning-graph](https://github.com/user-attachments/assets/0ac3052e-9f64-4d50-8243-2539f6145441)

[[ replay game ]](https://lichess.org/UH63opB8)

```
[Event "engine vs engine"]
[Site "Holland @ https://lichess.org/UH63opB8 "]
[Date "2024.09.20"]
[Round "?"]
[White "SF 17 NNUE"]
[Black "PeSTO v2.210"]
[WhiteElo "3600"]
[BlackElo "2992"]
[Result "1-0"]
[FEN "r7/3b4/2pN1pk1/2B1p1p1/1PB1P2p/p1K2P1P/P5P1/8 b - - 0 1"]
[GameDuration "00:09:56"]
[GameEndTime "2024-09-20T22:33:07.042 CEST"]
[GameStartTime "2024-09-20T22:23:10.862 CEST"]
[PlyCount "68"]
[SetUp "1"]
[TimeControl "300+3"]

1... Kh6 {-2.58/24 7.1s} 2. Be3 {+4.50/30 15s} Kg7 {-2.80/26 11s} 3. Kb3 {+4.75/26 6.4s} Kh7 {-3.36/26 37s} 4. Bc1 {+5.19/27 6.4s} Rd8 {-3.71/23 11s} 5. Bxa3 {+5.24/27 5.6s} Be6 {-3.74/25 14s} 6. Bxe6 {+5.55/25 6.4s} Rxd6 {-4.29/30 26s} 7. Bf5+ {+5.56/26 6.5s} Kg7 {-4.59/29 26s} 8. Kc2 {+5.67/25 7.8s} Rd4 {-4.61/26 14s} 9. Be6 {+5.84/27 7.8s} Rd8 {-4.40/26 16s} 10. Bc1 {+6.07/25 6.9s} Rd4 {-5.00/22 9.7s} 11. Bd2 {+6.37/26 6.6s} Kg6 {-5.69/24 13s} 12. a4 {+6.54/29 6.6s} Rd8 {-5.83/27 36s} 13. a5 {+6.88/28 8.1s} Re8 {-7.63/25 19s} 14. Bc4 {+7.12/28 7.4s} c5 {-7.94/24 27s} 15. bxc5 {+7.50/28 7.0s} Rc8 {-13.83/24 20s} 16. Be3 {+7.79/29 6.9s} Ra8 {-16.72/22 11s} 17. a6 {+7.97/29 7.2s} f5 {-21.49/25 15s} 18. exf5+ {+8.14/29 7.0s} Kxf5 {-14.71/23 18s} 19. Bd3+ {+8.23/28 7.0s} Ke6 {-14.83/22 6.7s} 20. Bxg5 {+8.29/28 8.6s} Rc8 {-9.52/23 8.1s} 21. Be3 {+8.54/28 7.6s} Rc7 {-14.56/22 8.2s} 22. Be4 {+M51/80 10s} Rf7 {-18.12/18 1.9s} 23. c6 {+M27/55 9.2s} Rg7 {-22.92/25 6.2s} 24. a7 {+M23/58 9.1s} Rg8 {-M24/22 0.36s} 25. Kc3 {+M21/58 9.1s} Rc8 {-M22/20 0.074s} 26. Bb6 {+M19/60 9.5s} Rf8 {-M20/18 0.007s} 27. c7 {+M17/66 9.0s} Kd7 {-M18/16 0.005s} 28. a8=Q {+M15/77 8.7s} Rxa8 {-M16/14 0.004s} 29. Bxa8 {+M13/111 8.3s} e4 {-M14/12 0.002s} 30. Bxe4 {+M11/242 8.7s} Kc8 {-M12/12 0.033s} 31. Bf5+ {+M9/245 1.8s} Kb7 32. c8=Q+ {+M7/245 0.058s} Kxb6 33. Bd3 {+M5/245 0.061s} Ka7 {-M6/4 0s} 34. Qc7+ {+M3/245 0.032s} Ka8 {-M4/2 0s} 35. Be4# {+M1/245 0.018s, White mates} 1-0
```

I have no clue how this info could help you "fix this problem", it's a position which needs "long-term vision".
i'm planning a tournament with this starting position where several strong engines must prove their 'insight' :
how to win with White ?

**Comment by Timmoth** [comment]
Such an incredible analysis, thank you! 

Yes that data is really helpful, I'll try and test it tonight, my suspicion is that it's either reaching it's max search depth, and would need to otherwise see further (I'll try bumping it up) Or it could just be the data gen I was using for that version didn't have great end game positions in it. I recently made a change that I think will help with that, currently training a new net, if successful it'll be out in v1.1.1 tonight. Finally, it could easily be the pruning, since I believe the aggressive pruning is part of what gives it's playstyle, it could also be pruning branches that it shouldn't.

**Comment by tissatussa** [comment]
> Such an incredible analysis, thank you!

i just decribed what i did : among the many games this one struck me, so i copied a FEN somewhere at the ending and performed that SF test.

> Yes that data is really helpful.

you mean it helps you improve the "long-term vision" in general ?
i doubt that, but it can be, let's say it will surprise me when it happens - again :-)
anyhow, i'm glad it gave you inspiration !

> I'll try and test it tonight, my suspicion is that it's either reaching it's max search depth, and would need to otherwise see further (I'll try bumping it up) Or it could just be the data gen I was using for that version didn't have great end game positions in it. I recently made a change that I think will help with that, currently training a new net, if successful it'll be out in v1.1.1 tonight. Finally, it could easily be the pruning, since I believe the aggressive pruning is part of what gives it's playstyle, it could also be pruning branches that it shouldn't.

i was testing too : i let Sapling play White in that FEN position against stronger engines and MOST OFTEN it can win but not always !? Remember eval is +6, so we could expect even a medium strong engine can always win with White, also against Big Brother .. i set 5m+3s, but normaly this TC is from start position, so now Sapling can think much longer and maybe THEN finds its way to victory ?! We have ratings for bullet, blitz, rapid and classic overall. Btw. in my tests i used v1.0.4 (256 Mb Hash, 2 threads) because that version gave us the FEN . I conclude Sapling CAN always win, even against SF 17, but only when it has enough time per move.

However, here's a game which quickly ended in a draw !? :

```
[Event "engine vs engine"]
[Site "Holland"]
[Date "2024.09.24"]
[Round "?"]
[White "Sapling v1.0.4 NNUE"]
[Black "Svart v6 NNUE"]
[WhiteElo "?"]
[BlackElo "3240"]
[Result "1/2-1/2"]
[FEN "r7/3b4/2pN1pk1/2B1p1p1/1PB1P2p/p1K2P1P/P5P1/8 b - - 0 1"]
[GameDuration "00:07:02"]
[TimeControl "300+3"]

1... Kh6 {-4.04/30 23s} 2. Bf7 {+6.19/31 13s} Kg7 {-4.00/30 7.8s}
3. Bb3 {+6.19/31 12s} Kh6 {-3.99/32 9.7s} 4. Kc2 {+6.19/31 12s}
Kh7 {-4.06/30 14s} 5. Bc4 {+6.19/30 12s} Rd8 {-4.09/29 11s}
6. Kc3 {+6.18/31 11s} Ra8 {-3.99/29 14s} 7. Kb3 {+6.18/32 11s}
Kg7 {-4.05/29 29s} 8. Kc2 {+6.18/33 11s} Kg6 {-3.99/31 26s}
9. Bf7+ {+6.18/30 10s} Kg7 {-4.17/28 9.5s} 10. Kc3 {+6.18/33 10s}
Kh7 {-4.22/28 5.9s} 11. Nf5 {+6.16/29 10s} Bc8 {-4.22/30 8.1s}
12. Bb3 {+6.15/29 9.8s} Bd7 {-3.72/30 8.4s} 13. Nd6 {+6.15/28 9.5s}
Kh6 {-0.03/61 14s} 14. Kd2 {+6.19/30 9.3s} Kg7 {-3.89/30 12s}
15. Bc4 {+6.17/30 9.1s} Kh7 {-3.95/30 12s} 16. Kc3 {+6.18/32 8.9s}
Kh6 {-0.07/55 17s} 17. Bf7 {+6.15/29 8.7s} Kg7 {-0.06/58 15s}
18. Bb3 {+6.16/30 8.5s} Kh6 {-0.04/60 11s, Draw by 3-fold repetition} 1/2-1/2
```

I don't know why Sapling v1.0.4 didn't win this one. Probably next time it will, against Svart (3240!) i mean, and this could be true for other engines also .. it's hard to image / find a way to prove a next engine version will act "better in general" and always win that position too. What do you think ?

And i have another position which is delicate. Once i wrote this Issue about it : [just win on the white squares](https://github.com/deanmchris/blunder/issues/13)

White to move and win.

![just-win-on-the-white-squares](https://github.com/user-attachments/assets/84941a12-4d7b-4444-b159-872e905799d6)

it's a rather 'technical' position, but nice, like a puzzle, far out .. human can FEEL the concerning 'pattern' and THEN prove f6 is the right continuation, but only ShashChess seems to find the key move f6 .. i also set MultiPV because without that, the engine might never imagine f6 being a 'candidate move' .. SF 17 NNUE can't find it ! Older SF 16.1 DOES find +M19 at high depth, but only when giving f6 as the solution : then SF must think as Black and only then finds the real eval value .. Maybe this is the kind of position you're lokking for when adjusting your code and training a new net .. as i wrote, i'm not into that, and let's keep it that way :-) 

Honestly, i like the way you elaborate on my input, you're passionated, i like it !
What's your own rating ?

---

BONUS
a vid from yesterday evening - sound on !

Chess : Decline the War

Recent own online chess game, 15 min + 10 sec. I played the White pieces and chose a rare variation against the Dutch Defence : 2. g4 ?! I remembered Blacks response 3...g3! is most accurate, not capturing pawn h3 but returning the gambit pawn. So my opponent didn't seem to be surprised, but i won the game.

animation image: ColdFusion
music: "Bold as Love" by Jimi Hendrix (1967)
2024@ArtFlow - all rights respected    
    
https://github.com/user-attachments/assets/6852e8e1-66e6-4873-b3f3-180193553115

[ [replay game](https://lichess.org/UsEIfzH8) ]


```
[Event "LiChess Rated rapid game"]
[Site "Holland"]
[Date "2024.09.24"]
[White "tissatussa"]
[Black "pichinzenayt"]
[WhiteElo "2013"]
[BlackElo "1957"]
[TimeControl "900+10"]
[ECO "A80"]
[Opening "Dutch Defense: Krejcik Gambit"]
[Result "1-0"]

1. d4 f5 2. g4 fxg4 3. h3 g3 4. fxg3 Nf6 5. Qd3 d6 6. Bg2 g6 7. Nc3 c6 8. a4 Bg7 9. b3 Na6 10. Ba3 O-O 11. O-O-O Qc7 12. Kb1 Bd7 13. e4 Rab8 14. Nge2 b5 15. axb5 cxb5 16. Na2 Qa5 17. b4 Qc7 18. g4 Rfc8 19. g5 Nh5 20. Bc1 Qc4 21. Bf3 Nxb4 22. Nxb4 Qxb4+ 23. Qb3+ Rc4 24. e5 Qxb3+ 25. cxb3 Rcc8 26. exd6 exd6 27. Bd5+ Kh8 28. Nf4 Bf5+ 29. Ka2 Ng3 30. Rhe1 Rc2+ 31. Kb1 Re2+ 32. Ka1 Bxd4+ 33. Rxd4 Rxe1 34. Kb2 Ne2 35. Bd2 Nxd4 36. Bxe1 a5 37. Bc3 Kg7 38. h4 Kf8 39. Bxd4 b4 40. h5 Rc8 41. Bc4 Re8 42. hxg6 hxg6 43. Nd5 Re4 44. Bf6 Be6 45. Be7+ Ke8 46. Bxd6 Kd7 47. Nf6+ Kxd6 48. Nxe4+ Ke5 49. Bxe6 Kxe6 50. Kc2 Kf5 51. Kd3 Ke5 52. Ke3 Kd5 53. Nd2 Ke5 54. Nc4+ Kf5 55. Nxa5 Kxg5 56. Nc6 Kh4 57. Nxb4 g5 58. Nd3 g4 59. b4 g3 60. Nf4 Kg4 61. b5 1-0
```

**Comment by Timmoth** [comment]
> you mean it helps you improve the "long-term vision" in general ?

It'll help me debug the issue by replaying the exact game and seeing where the search acts strangely 

> I conclude Sapling CAN always win, even against SF 17, but only when it has enough time per move.

Being written in dotnet it's a little harder to write highly optimized code compared to lower level languages, but there are still a few tricks i've got left so hopefully i'll be able to bring the NPS up a little in future versions 

> it's hard to image / find a way to prove a next engine version will act "better in general" and always win that position too. What do you think ?

This is true, all I can realistically do it play it against its past versions using a SPRT test, which will determine if it's better on average across many different scenarios. I'm partially writing the OSCCEL to add some more variation into those tests. But it is theoretically possible it'll regress in certain areas. Though I've raised that before in the SF discord and the consensus is that if it passes the SPRT test you can assert it is a legit improvement. I do however worry that some of these improvements may lead to it loosing its unique characteristics. 

Great video - Love Jimi!

**Comment by tissatussa** [comment]
So you like the music .. Right !
A quick search in my memory didn't give another chess video creation with Jimi, so i picked this one :

https://github.com/user-attachments/assets/9851a77e-60f1-462b-a5b2-8b57f0df50ae


[ also read my [BitChute description](https://www.bitchute.com/video/fsHS0Q7eXPH6) ]

**Comment by Timmoth** [comment]
Just gave a few of your videos a watch, cool stuff! Do you not wana host them on YouTube? Never heard of BitChute

**Comment by tissatussa** [comment]
> Do you not wana host them on YouTube? Never heard of BitChute

i did host many on YT but i always use media (images and music) that i like and find, and most of those have copyright, and YT don't like that .. i was banned several times .. but i only create what i want, no intention to make money out of it .. BitChute doesn't mind the copyrights (officially they do, but they keep my videos).

**Comment by tissatussa** [comment]
i don't wanna spoil this Issue with too many vids and other stuff, but here's the first "Ginger Boom" vid from 2017 :

https://github.com/user-attachments/assets/7d506681-a906-47ba-841f-7694b8d83f8a

**Comment by tissatussa** [comment]
@Timmoth i managed to compile the newest v1.1.2 into a single Linux file with help of https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli : i slightly adjusted the `Makefile` and `./Sapling/Sapling.csproj` and executed `make -j1 publish`. The binary is 70.3 Mb in size and runs fine in CuteChess GUI. I got a bunch of warnings but no errors.

**Comment by Timmoth** [comment]
Keep em coming! Cool to watch! 

Brilliant! Would you mind sharing the changes you had to make to the make file out of curiosity? Was it just the target platform to Linux-64 

Also yeah it's a rather large binary due to it being 'self contained' - essentially I bundle the dotnet runtime with the exe so it doesn't require it to be installed separately

**Comment by tissatussa** [comment]
> Keep em coming! Cool to watch!

i'm glad you react like that .. i saw your animation scripts, i like that! you must be an artist too .. these GitHub Issues sometimes tend to sidestep a lot, adding videos and more .. i always try to post relevant info in GitHub Issues because these are an archive also - users read them, looking for answers .. but i will upload a few more nice vids here (GitHub allows max 10Mb and offers a nice mediaplayer), since you seem to like my style .. not all people can stand two images next to eachother, both moving .. to me those animations can magically match, in sound and vision, and for many years now i learn how to handle existing (?) media synchronicities when editing - receiving back-to-the-future ..

here's one of my recent own games, i played the Black pieces .. also read the description [on BitChute](https://www.bitchute.com/video/KFiMtKVf8Xgv) .. White expected me to play (an early) c7-c5 but i thought it would be dangerous to open the center that way and i didn't .. also White didn't play c2-c4 himself for a long time, giving this game special tensions .. in the end i was winning, but the positions were difficult and delicate and i had little time .. it was a team event so i decided to make a draw by repetition by which we won the match :


https://github.com/user-attachments/assets/a08a0182-6995-48e9-a0e2-19ea4bbdfb49

> Would you mind sharing the changes you had to make to the make file out of curiosity? Was it just the target platform to Linux-64

i will post these code changes here this afternoon.

> ..it's a rather large binary due to it being 'self contained' - essentially I bundle the dotnet runtime with the exe so it doesn't require it to be installed separately

i think that's a perfect setup, we can easily handle 60Mb files nowadays ..

**Comment by tissatussa** [comment]
in `Makefile` i only changed OUTPUT_DIR path.

in `./Sapling/Sapling.csproj` i adjusted the `PropertyGroup`, i added these 3 lines :

```
<PublishSingleFile>true</PublishSingleFile>
<SelfContained>true</SelfContained>
<RuntimeIdentifier>linux-x64</RuntimeIdentifier>
```

then i compiled by :

```
$ make -j1 publish
```

it creates 1 single file of 70 Mb.

**Comment by tissatussa** [comment]
this way i also changed the code of v1.1.3 and compiling went well again, i even got much less warnings :

```
$ make -j1 publish
dotnet publish Sapling/Sapling.csproj -c Release --runtime linux-x64 --self-contained /p:Optimized=true /p:DeterministicBuild=true /p:ExecutableName= -o ./out
  Determining projects to restore...
  Restored /home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling.Engine/Sapling.Engine.csproj (in 691 ms).
  Restored /home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling/Sapling.csproj (in 691 ms).
/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling.Engine/Evaluation/NnueWeights.cs(45,20): warning CS8602: Dereference of a possibly null reference. [/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling.Engine/Sapling.Engine.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling.Engine/RepetitionDetector.cs(92,26): warning CS8509: The switch expression does not handle all possible values of its input type (it is not exhaustive). For example, the pattern '0' is not covered. [/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling.Engine/Sapling.Engine.csproj]
  Sapling.Engine -> /home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling.Engine/bin/Release/net8.0/Sapling.Engine.dll
  Successfully created package '/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling.Engine/bin/Release/SaplingEngine.1.1.0.nupkg'.
  Successfully created package '/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling.Engine/bin/Release/SaplingEngine.1.1.0.symbols.nupkg'.
/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling/UciEngine.cs(28,23): warning CS8602: Dereference of a possibly null reference. [/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling/Sapling.csproj]
/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling/Program.cs(15,34): warning CS8602: Dereference of a possibly null reference. [/home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling/Sapling.csproj]
  Sapling -> /home/roelof/Compiled/Sapling-Sapling-1.1.3/Sapling/bin/Release/net8.0/linux-x64/Sapling.dll
  Sapling -> /home/roelof/Compiled/Sapling-Sapling-1.1.3/out/
```

at this moment i let this v1.1.3 play some games ..

**Comment by Timmoth** [comment]
>  i like that! you must be an artist too

Thank you! Far from it, but I do enjoy certain creative coding tasks! Especially geometric stuff - pretty maths!

> this way i also changed the code of v1.1.3 and compiling went well again, i even got much less warnings :

Awesome! Glad it went smoothly for you! 

> at this moment i let this v1.1.3 play some games ..

I can't wait to hear how it goes! I'm excited to figure out what the bug was from the other issue you found, then will start on Corrhist!
