### ISSUE TITLE
lost for must-win ?

### ISSUE THREAD

**Issue by tissatussa** [Timmoth/Sapling#8]
recently i let Sapling v1.1.2 play a 5m3s game with Patricia, the new 'super agressive' engine, also with NN .. at one moment in the game Sapling was clearly better (+3) but for almost 50 moves no piece was captured nor pawn moved, so this would lead to a draw and Sapling decided to push a pawn, avoid the 50-move rule because it was winning and it 'thought' the remaining position had a lower eval (+2.5) but enough not to lose, or so .. against Patricia this didn't work out .. she provoked the complications, which were indeed hard to cope ..

at the end, in theory White was much better, but how ?
i have no clue how my description of this 'behaviour' can help you improve the engine, but here's the (long) game : https://lichess.org/4uUXF7xC

![lichess-graph](https://github.com/user-attachments/assets/27b14508-f527-415c-8541-0f43ede9eca6)

note: the Stockfish eval values on LiChess are much lower then Sapling' judgements

**Comment by Timmoth** [comment]
FYI - Sorry it's taken me a while to respond! Been very busy the last few days, will take some time tomorrow to get around to replying to all your feedback / insights!

**Comment by Timmoth** [comment]
Yep I've observed this myself too, it must have thought the position was slightly up to the depth it was searching, but that doesn't guarantee it is. If it knows it's down it will force a draw.

As the network gets better (what I've been working hard on the past few days) it should happen less and less.

I wonder if there is a threshold I could add, say if the evaluation is less then 10cp round down to 0, not sure how something like that would actually work out in practice mind you

**Comment by Timmoth** [comment]
Also just to keep you in the loop, I don't know that the latest version 1.1.2 will actually be stronger for all environments / time control. I've increased the size of the network quite significantly and if your using the avx256 version on a low powered machine I think it might be worse at short time control then v1.1.1

I hope by the end of the day I'll have implemented 'finny tables' which should speed up the network considerably, and hopefully have the best of both worlds- strong evaluation and deep search. 

Next after that is the corrhist, which together with the increased net should reduce the frequency of the above mentioned issue

**Comment by tissatussa** [comment]
> Yep I've observed this myself too..

OK ! i will close this Issue then.
All your info is a nice read, thanks.
